address=/chat.openai.com/0.0.0.0
address=/chatgpt.com/0.0.0.0
address=/openai.com/0.0.0.0
address=/oaistatic.com/0.0.0.0
address=/cdn.oaistatic.com/0.0.0.0

address=/chess.com/0.0.0.0
address=/netflix.com/0.0.0.0

address=/bard.google.com/0.0.0.0
address=/gemini.google.com/0.0.0.0
address=/claude.ai/0.0.0.0
address=/youtube.com/0.0.0.0
