address=/chat.openai.com/0.0.0.0
address=/chatgpt.com/0.0.0.0
address=/openai.com/0.0.0.0
address=/oaistatic.com/0.0.0.0
address=/cdn.oaistatic.com/0.0.0.0
address=/youtube.com/0.0.0.0

address=/chess.com/0.0.0.0
address=/netflix.com/0.0.0.0

address=/bard.google.com/0.0.0.0
address=/gemini.google.com/0.0.0.0
address=/claude.ai/0.0.0.0

address=/perplexity.ai/0.0.0.0
address=/poe.com/0.0.0.0
address=/you.com/0.0.0.0
address=/grok.com/0.0.0.0
address=/pi.ai/0.0.0.0
address=/character.ai/0.0.0.0
address=/jan.ai/0.0.0.0
address=/huggingface.co/0.0.0.0
address=/phind.com/0.0.0.0
address=/deepseek.com/0.0.0.0

address=/midjourney.com/0.0.0.0
address=/leonardo.ai/0.0.0.0
address=/playgroundai.com/0.0.0.0
address=/dreamstudio.ai/0.0.0.0
address=/artbreeder.com/0.0.0.0
address=/nightcafe.studio/0.0.0.0
address=/starryai.com/0.0.0.0
address=/recraft.ai/0.0.0.0
address=/mage.space/0.0.0.0


address=/runwayml.com/0.0.0.0
address=/pika.art/0.0.0.0
address=/synthesia.io/0.0.0.0
address=/heygen.com/0.0.0.0
address=/descript.com/0.0.0.0
address=/pictory.ai/0.0.0.0
address=/d-id.com/0.0.0.0
address=/veed.io/0.0.0.0

address=/elevenlabs.io/0.0.0.0
address=/murf.ai/0.0.0.0
address=/suno.ai/0.0.0.0
address=/aiva.ai/0.0.0.0
address=/voicemod.net/0.0.0.0


address=/copilot.github.com/0.0.0.0
address=/api.githubcopilot.com/0.0.0.0
address=/githubcopilot.com/0.0.0.0
address=/copilot-proxy.githubusercontent.com/0.0.0.0
address=/api.github.com/0.0.0.0
address=/githubusercontent.com/0.0.0.0


